language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m coverage run test.py 

after_script: coveralls